Documentation
yangsoosong/drone-localization pull request #14
Opened 2022-08-02 21:54 UTC by dlebedinsky

This contains a notebook with working motion control, and a notebook (localizer_cv.ipynb) with depth and detection integration.

2022-08-02 22:28 UTC, yangsoosong reviewed
You made changes to localizer.ipynb, this might cause merge conflict, do you want to name it differently?

2022-08-03 22:55 UTC, itsjohnward requested changes

2022-08-03 22:55 UTC, itsjohnward commented on localizer.ipynb
> +    "def record_drone_video2():\n",
unused method

2022-08-03 22:55 UTC, itsjohnward commented on README.md
> +1. Install Docker Desktop, Earthly, and jupyter lab.
* Don't need jupyter lab installed as of #9 because it's included in the docker image
* No longer need earthly installed as of #10

2022-08-03 22:55 UTC, itsjohnward commented on README.md
> +4. run `earthly +docker && ./run-notebook.sh` in the main branch of the project directory.
Remove `earthly +docker &&`

2022-08-03 22:55 UTC, itsjohnward commented on README.md
> +5. This will start a length installation process (about 20 minutes). At the end, you may be prompted to reboot. If so, repeat step 3 and run `./run-notebook.sh` in the project directory again.
Shouldn't be lengthy anymore without the earthly step, and shouldn't need to reboot

2022-08-03 22:55 UTC, itsjohnward commented on README.md
> +Are steps for M1 Macs different from Intel Macs?
Nope. Same for both.

1. Make sure homebrew's installed. If not,

```sh
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

2. Make sure Docker Desktop's installed. If not,

```
$ brew install --cask docker
```

3. Open Docker.app. Wait for it to start up, and allow privileged access and provide your password if prompted.

4. And then you can run the script:

```sh
$ ./run-notebook.sh
```

2022-08-03 23:11 UTC, itsjohnward commented on README.md
> +Are steps for M1 Macs different from Intel Macs?
Added this to a PR: #15

2022-08-03 23:30 UTC, itsjohnward commented on README.md
> +1. Install Docker Desktop, Earthly, and jupyter lab.
Updated in #15

2022-08-03 23:31 UTC, itsjohnward commented on README.md
> +4. run `earthly +docker && ./run-notebook.sh` in the main branch of the project directory.
Updated in #15

2022-08-03 23:31 UTC, itsjohnward commented on README.md
> +5. This will start a length installation process (about 20 minutes). At the end, you may be prompted to reboot. If so, repeat step 3 and run `./run-notebook.sh` in the project directory again.
Updated in #15

2022-08-05 02:06 UTC, closed without merging